### ISSUE TITLE
Router API register_model: incorrect order of "filter" functions parameters

### ISSUE THREAD

**Issue by tomaszn** [powered-by-wq/wq.io#10]
On /router page, section "Router API":

> filter    No-op.  The argument should be a function that accepts a request object and a queryset and filters the latter.

In 1.0b (at least) the function accepts queryset as the first arg, and the request as the second one.

**Comment by sheppard** [comment]
Good catch, thanks.  I fixed this in both the 0.8 and 1.0 docs.
